#!/bin/bash

# Quick Setup Script for Replay Attack Demo
# Usage: ./setup-demo.sh

set -e

echo "========================================"
echo "  Replay Attack Demo Setup"
echo "========================================"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if running in correct directory
if [ ! -f "tests/replay-attack-demo.js" ]; then
    echo -e "${RED}Error: Please run this script from the project root directory${NC}"
    echo "  cd /path/to/Realtime-Chat-System"
    echo "  ./tests/setup-demo.sh"
    exit 1
fi

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Error: Node.js is not installed${NC}"
    echo "  Please install Node.js: https://nodejs.org/"
    exit 1
fi

echo -e "${GREEN}✓${NC} Node.js found: $(node --version)"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}Error: npm is not installed${NC}"
    exit 1
fi

echo -e "${GREEN}✓${NC} npm found: $(npm --version)"

# Install dependencies
echo ""
echo "Installing dependencies..."
if [ -f "tests/package.json" ]; then
    cd tests
    npm install
    cd ..
else
    # Install globally in tests folder
    cd tests
    npm init -y
    npm install axios
    cd ..
fi

echo -e "${GREEN}✓${NC} Dependencies installed"

# Prompt for configuration
echo ""
echo "========================================"
echo "  Configuration"
echo "========================================"
echo ""

# VM1 URL
read -p "Enter VM1 URL (e.g., http://34.71.XXX.XXX:8029): " VM1_URL
if [ -z "$VM1_URL" ]; then
    VM1_URL="http://localhost:8029"
    echo -e "${YELLOW}Using default: $VM1_URL${NC}"
fi

# HMAC Secret
echo ""
echo "To find your HMAC secret key, run on VM1:"
echo "  docker exec backend_chat env | grep HMAC_SECRET_KEY"
echo ""
read -p "Enter HMAC_SECRET_KEY: " HMAC_SECRET

if [ -z "$HMAC_SECRET" ]; then
    echo -e "${RED}Error: HMAC_SECRET_KEY is required${NC}"
    exit 1
fi

# Create .env file for tests
cat > tests/.env << EOF
# Auto-generated by setup-demo.sh
VM1_URL=$VM1_URL
HMAC_SECRET_KEY=$HMAC_SECRET
EOF

echo -e "${GREEN}✓${NC} Configuration saved to tests/.env"

# Create run script
cat > tests/run-demo.sh << 'EOF'
#!/bin/bash

# Load environment variables
if [ -f .env ]; then
    export $(cat .env | grep -v '^#' | xargs)
fi

# Run demo
node replay-attack-demo.js
EOF

chmod +x tests/run-demo.sh

echo -e "${GREEN}✓${NC} Run script created: tests/run-demo.sh"

# Test connectivity
echo ""
echo "========================================"
echo "  Testing Connection"
echo "========================================"
echo ""

echo "Testing connection to $VM1_URL..."
if curl -s -o /dev/null -w "%{http_code}" "$VM1_URL/health" | grep -q "200\|404"; then
    echo -e "${GREEN}✓${NC} VM1 is reachable"
else
    echo -e "${YELLOW}⚠${NC} Cannot reach VM1 (this may be normal if you're not connected to VPN)"
    echo "  You can still run the demo when connected to the VM network"
fi

# Summary
echo ""
echo "========================================"
echo "  Setup Complete!"
echo "========================================"
echo ""
echo "To run the demo:"
echo ""
echo "  cd tests"
echo "  ./run-demo.sh"
echo ""
echo "Or manually:"
echo ""
echo "  export VM1_URL=\"$VM1_URL\""
echo "  export HMAC_SECRET_KEY=\"***\""
echo "  node tests/replay-attack-demo.js"
echo ""
echo -e "${GREEN}Happy testing!${NC}"
